reponseListe = ["Bien sur jeune padawan, la voici: ", 
    "Je trouve toujours ce que tu me demandes: ",
    "J'ai enfin trouvé ce que tu m'as demandé: ",
    "Je suis très intélligent, donc je trouve l'adresse que tu veux: ",
    "J'aime chercher ce que tu me demandes: ",
    "Je suis une carte ambulante pour vous servir: ",
    "Grandpy est un génie, il va te donner l'adresse demandé: ",
    "Arrête de regarder les 2 petits vieux dérrière et regarde l'adresse: ",
    "Pourquoi tu me demandes toujours des adresses facile à trouvé, regarde: ",
    "Elle n'était pas facile à trouvé, mais la voici: ",
    "Tu peux zoomé sur l'adresse avec ton curseur si tu es curieux: ",
    "Bien sur petit scarabé, la voici: "]